### ISSUE TITLE
Cannot redeclare static $my_attributes

### ISSUE THREAD

**Issue by chrxs** [intrip/laravel-single-table-inheritance#2]
Hi,

i'm having trouble implementing your single-table-inheritance package, hopefully I'm just missing something out! :)

I'm looking to have a Page model and a BlogPost model that both use the pages table.

I made my Page.php model just like your example Animal.php model, then the BlogPost.php model like your Cat.php model.

When I try to create a new Page but couldn't save it:

``` php
$page = new Page;
$page->name = 'Page 1';
$page->save();
```

this is the error I get:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Cannot redeclare static Jacopo\LaravelSingleTableInheritance\Models\Model::$my_attributes as non static Page::$my_attributes
```

but i'm not sure what it means, am I doing something wrong?

**Comment by intrip** [comment]
The problem is there is a misunderstood in the example(i'll fix that soon). What you have to declare attributes as static so for example:
protected static $my_attributes = array("attribute_name1","attribute_name2");

**Comment by chrxs** [comment]
Brilliant, thank you :smile: I did also have to add to the Page model:

``` php
protected $table = 'pages';
```
