### ISSUE TITLE
Compatibility with laravel 4.2

### ISSUE THREAD

**Issue by machomi** [intrip/laravel-single-table-inheritance#4]
I got an exception with Undefined class constant 'DELETED_AT'. Laravel 4.2 has a trait SoftDeletingTrait (see: http://laravel.com/docs/upgrade) instead of property. Are you planning to adjust your software to the new version of laravel?

**Comment by intrip** [comment]
Yes i'll fix that. Could you dump me the full error please? Ill fix it asap

**Comment by machomi** [comment]
Here it is a dump from laravel.log:

```
local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Undefined class constant 'DELETED_AT'' in /home/vagrant/Code/c4m_ssm/vendor/jacopo/laravel-single-table-inheritance/src/Jacopo/LaravelSingleTableInheritance/Models/Model.php:95
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
```

**Comment by bgraham1125** [comment]
I ran into the same issue.  What is you estimate for when you can have this fixed? I am very interested in using it in a project.  Thanks.

**Comment by intrip** [comment]
I'll handle that next week, can't do that before.

**Comment by intrip** [comment]
I've pushed a new version 1.1.0 with laravel 4.2 compatibility, please try it and tell me if you find any problems.

**Comment by bgraham1125** [comment]
Thank you for updating this.  As a test, I am trying to duplicate your example.  In a route I return $Animals to a view. With $Animals = Dog::all(); I get the error: 
The attribute food is non available. (View: /Applications/MAMP/htdocs/sti2/app/views/animals/index.blade.php).  
With $Animals=Cat::all(); the error is: 
The attribute collar is non available. (View: /Applications/MAMP/htdocs/sti2/app/views/animals/index.blade.php). 
When I use $Animals=Animal::all(), the view renders with no records. I am new to Laravel so would appreciate any assistance you could provide. Thank you.

**Comment by bgraham1125** [comment]
Please disregard the comment above.  It is now working.  Thank you.

**Comment by intrip** [comment]
Perfect. Closing issue then.
