### ISSUE TITLE
Laravel 5.0

### ISSUE THREAD

**Issue by bgraham1125** [intrip/laravel-single-table-inheritance#5]
I know you recently just updated this to work with Laravel 4.2.  Do you intend to update it to work with Laravel (4.3 / 5.0)?  Thank you.

**Comment by intrip** [comment]
I'll take a look and tell you if there's any big difference

**Comment by bgraham1125** [comment]
Thank you.  I appreciate it.

Bill

**Comment by bgraham1125** [comment]
Have you had a chance to look at this?

**Comment by intrip** [comment]
I took a fast look and i think i can say this version will support Laravel 5.0 without any big change.

**Comment by bgraham1125** [comment]
Great, that is good news.  The problem is it will not install with Composer into a Laravel 5 application.  The error message says It is looking for the wrong (older) versions of various libraries.

**Comment by intrip** [comment]
Yes when Laravel5 will be new main version i'll update composer dependency. Now is on ~4 that means every 4.x

**Comment by bgraham1125** [comment]
The last error message I received with  "jacopo/laravel-single-table-inheritance": "1.1.*" in the composer.json is:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jacopo/laravel-single-table-inheritance could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting

**Comment by intrip** [comment]
You're trying that with which laravel version?

**Comment by bgraham1125** [comment]
Here is the require statement:
"require": {
        "laravel/framework": "~5.0",
        "illuminate/html": "5.0._@dev",
        "jacopo/laravel-single-table-inheritance": "1.1._"
    },
aritsan reports:
Laravel Framework version 5.0-dev

**Comment by intrip** [comment]
Allright, at november when laravel 5 will be not dev i'll add support for that. For now it's only 4.*

**Comment by isaactinghong** [comment]
sorry, is the version going to be updated to ~5 for illuminate/support ?

**Comment by intrip** [comment]
Not immediately because i've some other projects as priority for now but it's in my todo list.

**Comment by isaactinghong** [comment]
okay, thanks for your effort in making this package anyway!!
